---
openapi: 3.0.3
tags: []
info:
  title: Access Tokens - OneLogin API
  description: 
      Generate an access token and refresh token that you can use to call our resource APIs.
      In order to use OneLogin APIs, new API Credentials are needed in order to exchange Access Tokens.
      This Collection uses version 2 of the OneLogin Generate Token endpoint.
  version: 2.0.0
  contact:
    name: "OneLogin Developers"
    url: "https://developers.onelogin.com/contact"
    email: "support@onelogin.com"

servers:
  - url: "https://{{api-domain}}"

components:
  securitySchemes:
    basicAuth:     # <-- arbitrary name for the security scheme
      type: http
      scheme: basic

paths:
  /auth/oauth2/v2/token:
    post:
      summary: Generate Tokens (Url Encoded)
      description: Generate Tokens (Url Encoded)
      operationId: generateTokensUrlEncoded
      security:
          - basicAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                grant_type:
                  type: string
                  example: client_credentials
            example:
              grant_type: client_credentials
      responses:
        "200":
          description: ""

  /auth/oauth2/revoke:
    post:
      summary: Revoke Tokens
      description: Revoke Tokens
      operationId: revokeTokens
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                access_token:
                  type: string
                  example: "{{access_token}}"
            example:
              access_token: "{{access_token}}"
      responses:
        "200":
          description: ""
  /auth/rate_limit:
    get:
      summary: Get Rate Limit
      description: Get Rate Limit
      operationId: getRateLimit
      responses:
        "200":
          description: ""