---
openapi: 3.0.3
info:
  title: Roles v2 - OneLogin API
  version: 2.0.0
  contact: {}
servers:
  - url: "https://{{api-domain}}/api/2"
security:
  - oAuth2ClientCredentials: []
paths:
  /roles:
    get:
      summary: List Roles
      description: List Roles
      operationId: listRoles
      parameters:
        - name: name
          in: query
          schema:
            type: string
        - name: app_id
          in: query
          schema:
            type: integer
            example: "{{app_id}}"
        - name: app_name
          in: query
          schema:
            type: string
        - name: fields
          in: query
          schema:
            type: string
      responses:
        "200":
          description: "Successfully fetched resource"
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create Role
      description: Create Role
      operationId: createRole
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                admins:
                  type: array
                  items: {}
                  example: []
                apps:
                  type: array
                  items: {}
                  example: []
                name:
                  type: string
                  example: Sample Role
                users:
                  type: array
                  items: {}
                  example: []
            example:
              admins: []
              apps: []
              name: Sample Role
              users: []
      responses:
        "201":
          description: "Successfully created role"
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  "/roles/:role_id":
    get:
      summary: Get Role
      description: Get Role
      operationId: getRole
      responses:
        "200":
          description: ""
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      summary: Update Role
      description: Update Role
      operationId: updateRole
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Updated Role Name
            example:
              name: Updated Role Name
      responses:
        "200":
          description: ""
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      summary: Delete Role
      description: Delete Role
      operationId: deleteRole
      responses:
        "200":
          description: ""
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    parameters:
      - name: role_id
        in: path
        required: true
        schema:
          type: string
          example: "{{role_id}}"
  "/roles/:role_id/admins":
    get:
      tags:
        - Admins
      summary: Get Role Admins
      description: Get Role Admins
      operationId: getRoleAdmins
      responses:
        "200":
          description: ""
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - Admins
      summary: Add Role Admins
      description: Add Role Admins
      operationId: addRoleAdmins
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: number
                example: 36216766
              example:
                - 36216766
            example:
              - 36216766
      responses:
        "200":
          description: ""
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - Admins
      summary: Remove Role Admins
      description: Remove Role Admins
      operationId: removeRoleAdmins
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: number
                example: 36216766
              example:
                - 36216766
            example:
              - 36216766
      responses:
        "200":
          description: ""
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    parameters:
      - name: role_id
        in: path
        required: true
        schema:
          type: string
          example: "{{role_id}}"
  "/roles/:role_id/apps":
    get:
      tags:
        - Apps
      summary: Get Role Apps
      description: Get Role Apps
      operationId: getRoleApps
      parameters:
        - name: assigned
          in: query
          schema:
            type: string
            example: "false"
      responses:
        "200":
          description: ""
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    put:
      tags:
        - Apps
      summary: Set Role Apps
      description: "Supply the full list of apps that should be assigned to this role. Apps will either be added or removed based on their presence in this list. "
      operationId: setRoleApps
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items: {}
              example: []
            example: []
      responses:
        "200":
          description: ""
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    parameters:
      - name: role_id
        in: path
        required: true
        schema:
          type: string
          example: "{{role_id}}"
  "/roles/:role_id/users":
    get:
      tags:
        - Users
      summary: Get Role Users
      description: Get Role Users
      operationId: getRoleUsers
      parameters:
        - name: name
          in: query
          schema:
            type: string
            example: Rich
        - name: include_unassigned
          in: query
          schema:
            type: string
            example: "true"
      responses:
        "200":
          description: ""
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      tags:
        - Users
      summary: Add Role Users
      description: Add Role Users
      operationId: addRoleUsers
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: number
                example: 60231059
              example:
                - 60231059
                - 60231067
            example:
              - 60231059
              - 60231067
      responses:
        "200":
          description: ""
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      tags:
        - Users
      summary: Remove Role Users
      description: Remove Role Users
      operationId: removeRoleUsers
      requestBody:
        content:
          application/json:
            schema:
              type: array
              items:
                type: number
                example: 60231067
              example:
                - 60231067
            example:
              - 60231067
      responses:
        "200":
          description: ""
        default:
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    parameters:
      - name: role_id
        in: path
        required: true
        schema:
          type: string
          example: "{{role_id}}"

components:
  securitySchemes:
    oAuth2ClientCredentials:
      type: oauth2
      description: See https://developers.onelogin.com/api-docs/1/oauth20-tokens/generate-tokens-2
      flows: 
        clientCredentials: 
          tokenUrl: https://api.{{region}}.onelogin.com/auth/oauth2/v2/token
          scopes: {} # Role APIs V2 do not use scopes.
  schemas:
    Error:
      type: object
      required:
        - statusCode
        - message
        - name
      properties:
        statusCode:
          type: integer
          format: int32
        message:
          type: string
        name:
          type: string

tags:
  - name: Apps
  - name: Users
  - name: Admins