---
openapi: 3.0.3
info:
  title: SAML Assertion
  version: 2.0.0
  contact: {}

servers:
  - url: "https://api.us.onelogin.com/api/2"
    description: "Production US API Auth Server"
  - url: "https://api.eu.onelogin.com/api/2"
    description: "Production EU API Auth Server"

security:
  - oAuth2ClientCredentials: []

paths:
  /saml_assertion:
    post:
      summary: Generate SAML Assertion
      description: Generate SAML Assertion
      operationId: generateSamlAssertion
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                app_id:
                  type: string
                  example: "{{app_id}}"
                password:
                  type: string
                  example: "{{password}}"
                subdomain:
                  type: string
                  example: "{{subdomain}}"
                username_or_email:
                  type: string
                  example: "{{username_or_email}}"
            example:
              app_id: "{{app_id}}"
              password: "{{password}}"
              subdomain: "{{subdomain}}"
              username_or_email: "{{username_or_email}}"
      responses:
        "200":
          description: ""
  /saml_assertion/verify_factor:
    post:
      summary: Verify Factor SAML
      description: Verify Factor SAML
      operationId: verifyFactorSaml
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                app_id:
                  type: string
                  example: "{{app_id}}"
                device_id:
                  type: string
                  example: "{{device_id}}"
                otp_token:
                  type: string
                  example: "{{otp_token}}"
                state_token:
                  type: string
                  example: "{{state_token}}"
            example:
              app_id: "{{app_id}}"
              device_id: "{{device_id}}"
              otp_token: "{{otp_token}}"
              state_token: "{{state_token}}"
      responses:
        "200":
          description: ""
tags: []
